apiVersion: v1
kind: Service
metadata:
  name: workflow-e
  namespace: namespace-workflow-1729120836230
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: workflow-e
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000