apiVersion: v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: contoso.<CLUSTER_SPECIFIC_DNS_ZONE>
      http:
        paths:
          - backend:
              serviceName: {{ .Chart.Name }}
              servicePort: http
            path: /
