apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}
